In [1]:
import math
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

### 1.3

#### 1.3.1

In [2]:
matrix_zeros_ones = np.zeros((8, 8))
matrix_zeros_ones

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
matrix_zeros_ones[::2, ::2] = 1
matrix_zeros_ones[1::2, 1::2] = 1

In [4]:
matrix_zeros_ones

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 1.3.2

In [5]:
matrix_zero_to_four = np.zeros((5,5))
matrix_zero_to_four += np.arange(5)
matrix_zero_to_four

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 1.3.3

In [6]:
matrix_random = np.random.random((3, 3, 3))
matrix_random

array([[[0.78108251, 0.10887329, 0.84674438],
        [0.39811203, 0.47015996, 0.99763018],
        [0.98639734, 0.30276709, 0.49529395]],

       [[0.46495396, 0.62433195, 0.64180902],
        [0.74108584, 0.52367533, 0.44076767],
        [0.041759  , 0.28353588, 0.31992404]],

       [[0.59397896, 0.62963985, 0.62831687],
        [0.81967927, 0.38988038, 0.42736777],
        [0.12156466, 0.13583452, 0.36473128]]])

#### 1.3.4

In [7]:
matrix_square_ones = np.zeros((8, 8))
matrix_square_ones[0] = 1
matrix_square_ones[::, 0] = 1
matrix_square_ones[-1] = 1
matrix_square_ones[::, -1] = 1
matrix_square_ones

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

#### 1.3.5

In [8]:
matrix_to_sort = np.random.random((5, 3))
matrix_to_sort

array([[0.75129665, 0.35475299, 0.30442921],
       [0.25512057, 0.73188838, 0.63945999],
       [0.27500268, 0.0676614 , 0.04607713],
       [0.10620171, 0.51107864, 0.10065413],
       [0.28873548, 0.11577471, 0.97560176]])

In [9]:
matrix_to_sort = np.sort(matrix_to_sort, axis=0)[::-1]
matrix_to_sort

array([[0.75129665, 0.73188838, 0.97560176],
       [0.28873548, 0.51107864, 0.63945999],
       [0.27500268, 0.35475299, 0.30442921],
       [0.25512057, 0.11577471, 0.10065413],
       [0.10620171, 0.0676614 , 0.04607713]])

#### 1.3.6

In [10]:
matrix_params = np.random.random((5, 5))
matrix_params

array([[0.4480874 , 0.47658972, 0.7208867 , 0.22948583, 0.07469512],
       [0.70920287, 0.47363544, 0.49614077, 0.72161844, 0.62703567],
       [0.89724946, 0.32934562, 0.979439  , 0.84117485, 0.24626559],
       [0.99507803, 0.23447123, 0.98898877, 0.68203455, 0.10370274],
       [0.47258347, 0.55906632, 0.67407868, 0.88137504, 0.05658576]])

In [11]:
matrix_params.shape

(5, 5)

In [12]:
matrix_params.size

25

In [13]:
matrix_params.dtype

dtype('float64')

### 2.3

#### 2.3.1

In [14]:
dot1 = [3, 4, 5]
dot2 = [0, 1, 2]

a = pd.Series(dot1)
b = pd.Series(dot2)

dot_distance = math.sqrt((b[0] - a[0])**2 +
                         (b[1] - a[1])**2 +
                         (b[2] - a[2])**2)
dot_distance

5.196152422706632

#### 2.3.2 - 2.3.3

In [15]:
german_df = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/887a65c5b48f3b259f39a7471e8da812c160470a/german.csv')
german_df

1   2  3   4  5  6  7  8  9  10  ...  15  16  17  18  19  20  21  22  23  \
0    1   6  4  12  5  5  3  4  1  67  ...   1   0   0   1   0   0   1   0   0   
1    2  48  2  60  1  3  2  2  1  22  ...   1   0   0   1   0   0   1   0   0   
2    4  12  4  21  1  4  3  3  1  49  ...   1   0   0   1   0   0   1   0   1   
3    1  42  2  79  1  4  3  4  2  45  ...   1   0   0   0   0   0   0   0   0   
4    1  24  3  49  1  3  3  4  4  53  ...   1   1   0   1   0   0   0   0   0   
..  ..  .. ..  .. .. .. .. .. ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..   
995  4  12  2  17  1  4  2  4  1  31  ...   1   0   0   1   0   0   1   0   1   
996  1  30  2  39  1  3  1  4  2  40  ...   1   0   1   1   0   0   1   0   0   
997  4  12  2   8  1  5  3  4  3  38  ...   1   0   0   1   0   0   1   0   0   
998  1  45  2  18  1  3  3  4  4  23  ...   1   0   0   1   0   0   0   0   0   
999  2  45  4  46  2  1  3  4  3  27  ...   1   0   1   1   0   0   1   0   0   

     y  
0    1  
1    1  
2    0  
3    1  
4    1  
..  ..  
995  0  
996  0  
997  1  
998  1  
999  1  

[1000 rows x 24 columns]

In [16]:
german_df.shape

(1000, 24)

In [17]:
german_df.describe()

1            2           3            4            5  \
count  1000.000000  1000.000000  1000.00000  1000.000000  1000.000000   
mean      2.577000    20.903000     2.54500    32.711000     2.105000   
std       1.257638    12.058814     1.08312    28.252605     1.580023   
min       1.000000     4.000000     0.00000     2.000000     1.000000   
25%       1.000000    12.000000     2.00000    14.000000     1.000000   
50%       2.000000    18.000000     2.00000    23.000000     1.000000   
75%       4.000000    24.000000     4.00000    40.000000     3.000000   
max       4.000000    72.000000     4.00000   184.000000     5.000000   

                 6           7            8            9           10  ...  \
count  1000.000000  1000.00000  1000.000000  1000.000000  1000.000000  ...   
mean      3.384000     2.68200     2.845000     2.358000    35.546000  ...   
std       1.208306     0.70808     1.103718     1.050209    11.375469  ...   
min       1.000000     1.00000     1.000000     1.000000    19.000000  ...   
25%       3.000000     2.00000     2.000000     1.000000    27.000000  ...   
50%       3.000000     3.00000     3.000000     2.000000    33.000000  ...   
75%       5.000000     3.00000     4.000000     3.000000    42.000000  ...   
max       5.000000     4.00000     4.000000     4.000000    75.000000  ...   

                15           16           17           18           19  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      1.037000     0.234000     0.103000     0.907000     0.041000   
std       0.188856     0.423584     0.304111     0.290578     0.198389   
min       1.000000     0.000000     0.000000     0.000000     0.000000   
25%       1.000000     0.000000     0.000000     1.000000     0.000000   
50%       1.000000     0.000000     0.000000     1.000000     0.000000   
75%       1.000000     0.000000     0.000000     1.000000     0.000000   
max       2.000000     1.000000     1.000000     1.000000     1.000000   

                20           21           22         23            y  
count  1000.000000  1000.000000  1000.000000  1000.0000  1000.000000  
mean      0.179000     0.713000     0.022000     0.2000     0.630000  
std       0.383544     0.452588     0.146757     0.4002     0.483046  
min       0.000000     0.000000     0.000000     0.0000     0.000000  
25%       0.000000     0.000000     0.000000     0.0000     0.000000  
50%       0.000000     1.000000     0.000000     0.0000     1.000000  
75%       0.000000     1.000000     0.000000     0.0000     1.000000  
max       1.000000     1.000000     1.000000     1.0000     1.000000  

[8 rows x 24 columns]

In [18]:
german_df.head()

1   2  3   4  5  6  7  8  9  10  ...  15  16  17  18  19  20  21  22  23  y
0  1   6  4  12  5  5  3  4  1  67  ...   1   0   0   1   0   0   1   0   0  1
1  2  48  2  60  1  3  2  2  1  22  ...   1   0   0   1   0   0   1   0   0  1
2  4  12  4  21  1  4  3  3  1  49  ...   1   0   0   1   0   0   1   0   1  0
3  1  42  2  79  1  4  3  4  2  45  ...   1   0   0   0   0   0   0   0   0  1
4  1  24  3  49  1  3  3  4  4  53  ...   1   1   0   1   0   0   0   0   0  1

[5 rows x 24 columns]

In [19]:
german_df.tail()

1   2  3   4  5  6  7  8  9  10  ...  15  16  17  18  19  20  21  22  23  \
995  4  12  2  17  1  4  2  4  1  31  ...   1   0   0   1   0   0   1   0   1   
996  1  30  2  39  1  3  1  4  2  40  ...   1   0   1   1   0   0   1   0   0   
997  4  12  2   8  1  5  3  4  3  38  ...   1   0   0   1   0   0   1   0   0   
998  1  45  2  18  1  3  3  4  4  23  ...   1   0   0   1   0   0   0   0   0   
999  2  45  4  46  2  1  3  4  3  27  ...   1   0   1   1   0   0   1   0   0   

     y  
995  0  
996  0  
997  1  
998  1  
999  1  

[5 rows x 24 columns]

In [20]:
german_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       1000 non-null   int64
 1   2       1000 non-null   int64
 2   3       1000 non-null   int64
 3   4       1000 non-null   int64
 4   5       1000 non-null   int64
 5   6       1000 non-null   int64
 6   7       1000 non-null   int64
 7   8       1000 non-null   int64
 8   9       1000 non-null   int64
 9   10      1000 non-null   int64
 10  11      1000 non-null   int64
 11  12      1000 non-null   int64
 12  13      1000 non-null   int64
 13  14      1000 non-null   int64
 14  15      1000 non-null   int64
 15  16      1000 non-null   int64
 16  17      1000 non-null   int64
 17  18      1000 non-null   int64
 18  19      1000 non-null   int64
 19  20      1000 non-null   int64
 20  21      1000 non-null   int64
 21  22      1000 non-null   int64
 22  23      1000 non-null   int64
 23  y       1000 n

In [21]:
german_df.iloc[3:5]

1   2  3   4  5  6  7  8  9  10  ...  15  16  17  18  19  20  21  22  23  y
3  1  42  2  79  1  4  3  4  2  45  ...   1   0   0   0   0   0   0   0   0  1
4  1  24  3  49  1  3  3  4  4  53  ...   1   1   0   1   0   0   0   0   0  1

[2 rows x 24 columns]

In [22]:
german_y_df = german_df[german_df['y'] == 1].head()
german_y_df

1   2  3   4  5  6  7  8  9  10  ...  15  16  17  18  19  20  21  22  23  y
0  1   6  4  12  5  5  3  4  1  67  ...   1   0   0   1   0   0   1   0   0  1
1  2  48  2  60  1  3  2  2  1  22  ...   1   0   0   1   0   0   1   0   0  1
3  1  42  2  79  1  4  3  4  2  45  ...   1   0   0   0   0   0   0   0   0  1
4  1  24  3  49  1  3  3  4  4  53  ...   1   1   0   1   0   0   0   0   0  1
6  4  24  2  28  3  5  3  4  2  53  ...   1   0   0   1   0   0   1   0   0  1

[5 rows x 24 columns]

In [23]:
german_y_df.describe()

1          2         3          4         5    6         7  \
count  5.00000   5.000000  5.000000   5.000000  5.000000  5.0  5.000000   
mean   1.80000  28.800000  2.600000  45.600000  2.200000  4.0  2.800000   
std    1.30384  16.649324  0.894427  26.330591  1.788854  1.0  0.447214   
min    1.00000   6.000000  2.000000  12.000000  1.000000  3.0  2.000000   
25%    1.00000  24.000000  2.000000  28.000000  1.000000  3.0  3.000000   
50%    1.00000  24.000000  2.000000  49.000000  1.000000  4.0  3.000000   
75%    2.00000  42.000000  3.000000  60.000000  3.000000  5.0  3.000000   
max    4.00000  48.000000  4.000000  79.000000  5.000000  5.0  3.000000   

              8         9         10  ...   15        16   17        18   19  \
count  5.000000  5.000000   5.000000  ...  5.0  5.000000  5.0  5.000000  5.0   
mean   3.600000  2.000000  48.000000  ...  1.0  0.200000  0.0  0.800000  0.0   
std    0.894427  1.224745  16.552945  ...  0.0  0.447214  0.0  0.447214  0.0   
min    2.000000  1.000000  22.000000  ...  1.0  0.000000  0.0  0.000000  0.0   
25%    4.000000  1.000000  45.000000  ...  1.0  0.000000  0.0  1.000000  0.0   
50%    4.000000  2.000000  53.000000  ...  1.0  0.000000  0.0  1.000000  0.0   
75%    4.000000  2.000000  53.000000  ...  1.0  0.000000  0.0  1.000000  0.0   
max    4.000000  4.000000  67.000000  ...  1.0  1.000000  0.0  1.000000  0.0   

        20        21   22   23    y  
count  5.0  5.000000  5.0  5.0  5.0  
mean   0.0  0.600000  0.0  0.0  1.0  
std    0.0  0.547723  0.0  0.0  0.0  
min    0.0  0.000000  0.0  0.0  1.0  
25%    0.0  0.000000  0.0  0.0  1.0  
50%    0.0  1.000000  0.0  0.0  1.0  
75%    0.0  1.000000  0.0  0.0  1.0  
max    0.0  1.000000  0.0  0.0  1.0  

[8 rows x 24 columns]

### 3.3

#### 3.3.2

In [24]:
url  = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
data = pd.read_csv(url)

In [25]:
feature_one = 'sepal_length_cm'
feature_two = 'sepal_width_cm'
features_scaled = data[[feature_one, feature_two]]
features_scaled.head()

sepal_length_cm  sepal_width_cm
0              5.1             3.5
1              4.9             3.0
2              4.7             3.2
3              4.6             3.1
4              5.0             3.6

In [26]:
scaler_minmax = MinMaxScaler()
scaler_z = StandardScaler()

In [27]:
features_scaled[feature_one] = scaler_minmax.fit_transform(features_scaled[[feature_one]])
features_scaled[feature_one].head()

C:\Users\pyramidheadshark\AppData\Local\Temp\ipykernel_5596\3253505934.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features_scaled[feature_one] = scaler_minmax.fit_transform(features_scaled[[feature_one]])


0    0.222222
1    0.166667
2    0.111111
3    0.083333
4    0.194444
Name: sepal_length_cm, dtype: float64

In [28]:
features_scaled[feature_two] = scaler_z.fit_transform(features_scaled[[feature_two]])
features_scaled[feature_two].head()

C:\Users\pyramidheadshark\AppData\Local\Temp\ipykernel_5596\584001785.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features_scaled[feature_two] = scaler_z.fit_transform(features_scaled[[feature_two]])


0    1.032057
1   -0.124958
2    0.337848
3    0.106445
4    1.263460
Name: sepal_width_cm, dtype: float64

In [29]:
features_scaled.head()

sepal_length_cm  sepal_width_cm
0         0.222222        1.032057
1         0.166667       -0.124958
2         0.111111        0.337848
3         0.083333        0.106445
4         0.194444        1.263460